configurable timezone for filesystem build log
jenkinsci/timestamper-plugin pull request #105
Opened 2021-02-26 03:43 UTC by JackYou2020

currently, we can't configure timezone for initial build log 
we need to get run time log with following API, it will get initial log which timezone always UTC
http://jenkins_url/job/job_id/builds_id/execution/node/<node_id>/log/logText/progressiveText

so I try to make change to add timezone to control filesystem build log timezone. so get correct time log. 
any comments?

2021-02-26 04:13 UTC, JackYou2020 commented
@jglick  can you review it?

2021-02-26 16:50 UTC, jglick commented
I am not a maintainer.

2021-02-26 16:51 UTC, jglick requested changes
The log file should always use UTC. Particular displays may use the browser’s local time, etc.

2021-02-27 01:38 UTC, JackYou2020 commented
@jglick  I know that ,this timestamper is to convert initial log to localtime.  but my request is to get running time log from each stage
like http://jenkins_url/job/job_id/builds_id/execution/node/<node_id>/log/logText/progressiveText
it will get initial log
is there other api to get stage log?

2021-03-01 00:09 UTC, jglick commented
Step/node you mean, not stage? Not sure what you mean by “initial log”. Perhaps the plugin maintainer understands what this request is about better than I do.

2021-03-01 02:47 UTC, JackYou2020 commented
@jglick  "iniital log" is build log from filesystem which timezone is UTC.  
I tried API http://jenkins_url/job/job_id/builds_id/execution/node/<node_id>/log 
it just get log with html format.  I'd like to get plain text log.  so add "logText/progressiveText". but as I mentined above ,it is from file system build log.  so this is why I suggest there provides timezone params to GlobalDecorator.java

2021-03-01 16:18 UTC, jglick commented
The filesystem format is an implementation detail. I seem to recall that there are some RESTish APIs for accessing the log but I do not recall details.

2022-08-28 18:34 UTC, closed without merging